# Generated by Django 6.0.1 on 2026-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
